ConnectionStrings:
  ServiceDB: "postgres://postgres:1234@localhost/UsersDb?sslmode=disable"
HTTPServer:
  Url: "localhost:1000"
EnvironmentVariables:
  Environment: "development"
Logs:
  Path: ""
  Level: error
  MaxAge: 1
  MaxBackups: 4

